from typing import List, Literal, Optional, Union

from ontology import NodeLabel
from pydantic import BaseModel, Field


class TraversalStep(BaseModel):
    direction: Literal["OUT", "IN", "BOTH"] = "OUT"
    relationship_hint: str = Field(
        ...,
        description="Natural language description of the link (e.g., 'competitors', 'holdings')",
    )
    target_label: NodeLabel


class QueryFilter(BaseModel):
    property: str
    operator: Literal["EQ", "GT", "LT", "CONTAINS"]
    value: Union[str, int, float]


class QueryPlan(BaseModel):
    """The structured plan for graph traversal generated by the Agent."""

    start_node_label: NodeLabel
    start_node_identifier: str = Field(
        ...,
        description="The name or ticker of the starting node (e.g., 'AAPL', 'Tesla')",
    )
    traversal_path: List[TraversalStep]
    filters: Optional[List[QueryFilter]] = None
    return_target: Literal["node_properties", "neighbors", "path"] = "node_properties"
    limit: int = 5
