from enum import Enum
from typing import List, Literal

from pydantic import BaseModel, Field


class NodeLabel(str, Enum):
    USER = "User"
    ASSET = "Asset"
    SECTOR = "Sector"
    CONCEPT = "Concept"
    DOCUMENT = "Document"
    METRIC = "Metric"


class RelationshipType(str, Enum):
    # User-Centric
    HAS_POSITION = "HAS_POSITION"
    WATCHING = "WATCHING"
    AVOIDS = "AVOIDS"

    # Market-Structural
    OPERATES_IN = "OPERATES_IN"
    COMPETES_WITH = "COMPETES_WITH"
    AFFECTS = "AFFECTS"
    HAS_METRIC = "HAS_METRIC"

    # Bridge
    MENTIONS = "MENTIONS"


# Descriptions used for Dynamic Semantic Mapping (No hardcoded dicts)
RELATIONSHIP_DESCRIPTIONS = {
    RelationshipType.HAS_POSITION: "The user owns, holds, or has an investment in this asset.",
    RelationshipType.WATCHING: "The user is tracking, interested in, or monitoring this asset.",
    RelationshipType.AVOIDS: "The user dislikes, wants to exclude, or is avoiding this asset/sector.",
    RelationshipType.COMPETES_WITH: "Companies that are rivals, competitors, or in the same niche.",
    RelationshipType.AFFECTS: "How a macro concept or event impacts an asset or sector.",
}


class TraversalStep(BaseModel):
    direction: Literal["OUT", "IN", "BOTH"] = "OUT"
    relationship_hint: str = Field(
        ..., description="Natural language hint: 'competitors', 'holdings'"
    )
    target_label: NodeLabel


class QueryPlan(BaseModel):
    """The DSL generated by the Orchestrator Agent"""

    start_node_label: NodeLabel
    start_node_identifier: str = Field(..., description="e.g. 'Apple' or 'User_123'")
    traversal_path: List[TraversalStep] = Field(default_factory=list)
    limit: int = 5
