"""
api/services/analysis_stream_service.py

Drives OrchestratorAgent.run() and emits SSE frames as analysis progresses.

SSE event sequence
──────────────────
  {"type": "init",    "data": {ticker, companyName, currentPrice, ...}}
  {"type": "chart",   "data": [{time, price}, ...]}
  {"type": "agent",   "data": AgentAnalysis}          — one frame per agent
  {"type": "summary", "data": {coreNarrative, agentConsensus, verdict}}
  {"type": "done",    "data": null}
  {"type": "error",   "data": {"message": str}}        — on failure only

Design decisions
────────────────
• Instantiated per-request via FastAPI Depends() — not at module level.
  This ensures OrchestratorAgent() is constructed only after
  service_manager.startup() has completed (lifespan guarantee).

• Heartbeat is implemented as a background asyncio.Task that writes SSE
  comment lines (": keep-alive") to a shared asyncio.Queue, which the
  generator yields from.  This matches the existing EventBroadcaster/SSE
  pattern in the codebase and correctly keeps the TCP connection alive
  without requiring the generator to own a second parallel coroutine path.

• Market data (init + chart) is fetched concurrently with agent startup
  using asyncio.gather so the frontend receives the price card before the
  LLM pipeline completes.

• DataFrames never cross this boundary raw — they are converted to table
  dicts by ResponseAdapter before being serialised to JSON.
"""

from __future__ import annotations

import asyncio
import json
from typing import AsyncIterator, Optional

from langchain_core.messages import HumanMessage

from core.services import service_manager
from api.services.response_adapter import ResponseAdapter
from core.memory.sessions.session_service import SessionService
from core.agents.models.base_agent_models import AgentSentiment
from core.agents.orchestrator_agent import OrchestratorAgent
from core.logger import get_logger

logger = get_logger(__name__)

_KEEPALIVE_INTERVAL = 15.0  # seconds between SSE comment heartbeats


def _sse(event_type: str, data: object) -> str:
    """Format a single SSE data frame."""
    payload = json.dumps({"type": event_type, "data": data}, default=str)
    return f"data: {payload}\n\n"


def _sse_comment(text: str = "keep-alive") -> str:
    """SSE comment — ignored by EventSource but keeps the TCP connection open."""
    return f": {text}\n\n"


class AnalysisStreamService:
    """
    Drives one analysis turn and yields SSE frames.

    Instantiated per-request by FastAPI Depends() — see api/deps.py.
    The underlying singletons (OrchestratorAgent, service_manager resources)
    are safe to construct here because the lifespan hook guarantees
    service_manager.startup() has already completed before any request arrives.
    """

    def __init__(self) -> None:
        # Each request gets its own OrchestratorAgent wrapper; the heavy
        # resources (LLM, Neo4j, Chroma) live in service_manager singletons.
        self._orchestrator = OrchestratorAgent()
        self._market_svc = service_manager.get_market_data_service()
        self._adapter = ResponseAdapter()

    async def stream(
        self,
        *,
        query: str,
        user_email: str,
        conversation_id: str,
        ticker: Optional[str],
        session_svc: SessionService,
    ) -> AsyncIterator[str]:
        """
        Async generator that yields SSE frames.

        The caller wraps this in fastapi.responses.StreamingResponse with
        media_type="text/event-stream".

        Parameters
        ----------
        query           : Raw user query string.
        user_email      : Authenticated user identity (from JWT sub claim).
        conversation_id : Stable UUID for this conversation (generated by router).
        ticker          : Optional ticker extracted from the query — drives the
                          market data prefetch.
        session_svc     : Injected SessionService for post-analysis persistence.
        """
        # ── Heartbeat task ─────────────────────────────────────────────────────
        # Writes ": keep-alive\n\n" comments into a queue every 15 s.
        # The generator below drains this queue between substantive frames.
        heartbeat_queue: asyncio.Queue[str] = asyncio.Queue()

        async def _heartbeat() -> None:
            while True:
                await asyncio.sleep(_KEEPALIVE_INTERVAL)
                await heartbeat_queue.put(_sse_comment())

        heartbeat_task = asyncio.create_task(_heartbeat(), name="sse_heartbeat")

        async def _drain_heartbeats() -> AsyncIterator[str]:
            """Yield any pending heartbeat comments without blocking."""
            while not heartbeat_queue.empty():
                yield await heartbeat_queue.get()

        try:
            # ── Step 1: Market data (parallel with agent warm-up) ──────────────
            if ticker:
                try:
                    quote, chart = await asyncio.wait_for(
                        asyncio.gather(
                            self._market_svc.get_quote(ticker),
                            self._market_svc.get_intraday(ticker),
                        ),
                        timeout=10.0,
                    )
                    yield _sse("init", quote)
                    async for hb in _drain_heartbeats():
                        yield hb
                    yield _sse("chart", chart)
                except asyncio.TimeoutError:
                    logger.warning("Market data timeout for %s — proceeding", ticker)
                    yield _sse("init", {"ticker": ticker, "companyName": ticker})
                except Exception as exc:
                    logger.error("Market data fetch failed: %s", exc)
                    yield _sse("init", {"ticker": ticker, "companyName": ticker})
            else:
                # No ticker — emit a minimal init so the frontend initialises
                yield _sse("init", {"ticker": "", "companyName": ""})

            async for hb in _drain_heartbeats():
                yield hb

            # ── Step 2: Run orchestrator ────────────────────────────────────────
            messages = [HumanMessage(content=query)]
            final_response = await self._orchestrator.run(
                messages=messages,
                conversation_id=conversation_id,
                user_email=user_email,
            )

            async for hb in _drain_heartbeats():
                yield hb

            # ── Step 3: Emit per-agent results ──────────────────────────────────
            # Collect sentiments for the summary verdict derivation
            agent_sentiments: dict[str, Optional[AgentSentiment]] = {}

            for agent_name, output in (final_response.agent_outputs or {}).items():
                analysis_text = getattr(output, "analysis", "") or ""
                # Pull the structured sentiment stored on the agent output model
                sentiment: Optional[AgentSentiment] = getattr(output, "sentiment", None)
                agent_sentiments[agent_name] = sentiment

                sources = getattr(output, "sources", []) or []
                financial_data = getattr(output, "financial_data", None)

                agent_payload = self._adapter.to_agent_analysis(
                    agent_name=agent_name,
                    analysis_text=analysis_text,
                    sources=sources,
                    financial_data=financial_data,
                    ticker=ticker,
                    sentiment=sentiment,
                )
                yield _sse("agent", agent_payload)
                async for hb in _drain_heartbeats():
                    yield hb

            # ── Step 4: Emit summary ────────────────────────────────────────────
            summary_payload = self._adapter.to_summary(
                raw_summary=final_response.summary or "",
                agent_analyses={
                    name: getattr(out, "analysis", "")
                    for name, out in (final_response.agent_outputs or {}).items()
                },
                agent_sentiments=agent_sentiments,
            )
            yield _sse("summary", summary_payload)

            async for hb in _drain_heartbeats():
                yield hb

            # ── Step 5: Persist session ─────────────────────────────────────────
            try:
                await session_svc.save_analysis(
                    user_email=user_email,
                    conversation_id=conversation_id,
                    query=query,
                    ticker=ticker,
                    summary_text=final_response.summary or "",
                )
            except Exception:
                logger.exception(
                    "AnalysisStreamService: session save failed (non-fatal)"
                )

            yield _sse("done", None)

        except Exception as exc:
            logger.exception("AnalysisStreamService.stream: unhandled error")
            yield _sse("error", {"message": str(exc)})

        finally:
            heartbeat_task.cancel()
            try:
                await heartbeat_task
            except asyncio.CancelledError:
                pass



