[neo4j]
url = "neo4j+ssc://875c69db.databases.neo4j.io"
username = "neo4j"
password = "lUITZV_f36_tj0UTDkhAclowmR-lbSeTSEFrHq6XAkk"

[google]
api_key = "AIzaSyBye6ZfrCczo08r5xf9UVzyjYyVKOyFZiE"

[supabase]
url = "https://tmehgrbfkfdqvylkzwli.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtZWhncmJma2ZkcXZ5bGt6d2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MDc2MDgsImV4cCI6MjA3ODE4MzYwOH0.75SOXXp3TaID1baKc6Ztj72iggDtrYxK5XQzL-M7W0w"